// Generated by Wrangler by running `wrangler types`

interface Env {
	JETSTREAM_CONSUMER: DurableObjectNamespace<import("./src/index").JetstreamConsumer>;
	DB: D1Database;
	RESOLUTION_QUEUE: Queue;
}
